### ISSUE TITLE
Completed User Auth Feature

### ISSUE THREAD

**Issue by rgltalatala** [rgltalatala/Ravebrite#2]
Hi Justin, 

I have just completed my User Auth feature and am ready to move on to my events MVP.

**Comment by jmeyer90** [comment]
User Auth Review:

* When rendering errors and switching forms, we get the following error in the console: 
    * Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    * This is most likely due to how we're clearing our errors. This does not have to be done with an asynchronous function.
* Our session pages and navbar should be styled to more closely resemble the eventbrite webpages, especially concerning the sizing and placement of items on the page. We will be having a CSS lecture tomorrow. Please attend this lecture, and afterwards we will expect your clone to have near pixel perfect styling.

**Comment by rgltalatala** [comment]
Hi Justin, 

I've gone ahead and implemented the above suggestions and was able to resolve the errors that I came across.  The nav bar is very rudimentary in that it only includes the logo of the website along with a dropdown for a logout button with empty links as placeholders which will be replaced with links to user show/bookmarks/registrations.  Please let me know your thoughts, thanks in advance!

**Comment by jmeyer90** [comment]
Everything looks great! Feel free to move on to your next MVP.
